name: Rust

on:
  push:
    branches: [ main, rollback-update ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Toolchain
      run: rustup install nightly-i686-pc-windows-msvc
    - name: Build
      run: cargo +nightly-i686-pc-windows-msvc build --release --verbose
    - name: Run tests
      run: cargo +nightly-i686-pc-windows-msvc test --verbose
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Xrd Mod
        path: |
          target/i686-pc-windows-msvc/release/rev2hook.dll
